# language: node_js

# install:
#   - npm install
# script:
#   - npm run test

sudo: required

services:
  - docker

script:
  # - docker build -t tracker-api .
  # - docker images tracker-api

  - docker-compose build
  - docker-compose up -d mongo

  - ls -la

  - npm run test
