version: "3"

services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    depends_on:
      - mongo

  api-test:
    container_name: api-test
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - "8080:8080"

    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
